### ISSUE TITLE
spacy-wrap fail in some cases on long sequences

### ISSUE THREAD

**Issue by MWMWM** [KennethEnevoldsen/spacy-wrap#109]
## How to reproduce the behaviour
```
import spacy
import spacy_wrap

nlp = spacy.blank("fr")
config = {"model": {"name": "Jean-Baptiste/camembert-ner"}}
nlp.add_pipe("token_classification_transformer", config=config)

text = """
brice hansemann vice president charge de l'instruction a meaux 77100
information ouverte contre : x se disant prazaru margarita, x se disant adi popa, x se disant chica florin, x se disant tavu anarena, x se disant adan alexandra, x se disant kati enesa, x se disant alin alexandro, x
pour : vols en reunion, tentative de vols en reunion, refus de se soumettre aux operations de prelevement externe necessaire a la realisation d'examen technique et scientifique de comparaison avec les traces et indices preleves lors d'une enquete judiciaire, vols en bande organisee, traite des etres humains en bande organisee, recels en bande organisee de bien provenant d'un delit, delaissement de mineurs
mission : voir commission rogatoire jointe.
"""

nlp(text)
```
results in 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "xxx/site-packages/spacy/language.py", line 1031, in __call__
    error_handler(name, proc, [doc], e)
  File "xxx/site-packages/spacy/util.py", line 1670, in raise_error
    raise e
  File "xxx/site-packages/spacy/language.py", line 1026, in __call__
    doc = proc(doc, **component_cfg.get(name, {}))  # type: ignore[call-arg]
  File "xxx/site-packages/spacy_wrap/pipeline_component_tok_clf.py", line 391, in __call__
    self.set_annotations([doc], outputs)
  File "xxx/site-packages/spacy_wrap/pipeline_component_tok_clf.py", line 208, in set_annotations
    iob_tags, iob_prob = self.convert_to_token_predictions(
  File "xxx/site-packages/spacy_wrap/pipeline_component_tok_clf.py", line 275, in convert_to_token_predictions
    agg_token_logits = agg(logits[align.data[:, 0]])
IndexError: index 177 is out of bounds for axis 0 with size 176
```
while 
```
from transformers import AutoTokenizer, AutoModelForTokenClassification, pipeline
tokenizer = AutoTokenizer.from_pretrained("Jean-Baptiste/camembert-ner")
model = AutoModelForTokenClassification.from_pretrained("Jean-Baptiste/camembert-ner")
nlp = pipeline('ner', model=model, tokenizer=tokenizer, aggregation_strategy="simple")
text = """
brice hansemann vice president charge de l'instruction a meaux 77100
information ouverte contre : x se disant prazaru margarita, x se disant adi popa, x se disant chica florin, x se disant tavu anarena, x se disant adan alexandra, x se disant kati enesa, x se disant alin alexandro, x
pour : vols en reunion, tentative de vols en reunion, refus de se soumettre aux operations de prelevement externe necessaire a la realisation d'examen technique et scientifique de comparaison avec les traces et indices preleves lors d'une enquete judiciaire, vols en bande organisee, traite des etres humains en bande organisee, recels en bande organisee de bien provenant d'un delit, delaissement de mineurs
mission : voir commission rogatoire jointe.
"""
nlp(text)
```
works fine

## Your Environment
* Operating System: Linux-5.15.0-58-generic-x86_64-with-glibc2.31
* Python Version Used: 3.9.16
* spaCy Version Used: 3.4.4
* spaCy-wrap Version Used: 1.4.0

**Comment by willadamskeane** [comment]
Running into this issue as well!

**Comment by KennethEnevoldsen** [comment]
I actually solved this bug 4 days ago. So simpy upgrading to spacy-wrap 1.4.1 should solve this issue. It is because spacy-wrap when encounting very long sequences (128 wp or longer) tried to split into 128 wp sequence (with some overlap). This is done to handle arbitrarily long sequences, but I had an error in the handling which the test did not catch. 

It should now work (using spacy-wrap 1.4.1):

```
import spacy
import spacy_wrap

nlp = spacy.blank("fr")
config = {"model": {"name": "Jean-Baptiste/camembert-ner"}}
nlp.add_pipe("token_classification_transformer", config=config)

# duplicated the text to show that it 
text = """
brice hansemann vice president charge de l'instruction a meaux 77100
information ouverte contre : x se disant prazaru margarita, x se disant adi popa, x se disant chica florin, x se disant tavu anarena, x se disant adan alexandra, x se disant kati enesa, x se disant alin alexandro, x
pour : vols en reunion, tentative de vols en reunion, refus de se soumettre aux operations de prelevement externe necessaire a la realisation d'examen technique et scientifique de comparaison avec les traces et indices preleves lors d'une enquete judiciaire, vols en bande organisee, traite des etres humains en bande organisee, recels en bande organisee de bien provenant d'un delit, delaissement de mineurs
mission : voir commission rogatoire jointe.
"""

doc = nlp(text)

print(doc.ents)
```
Results in:
```
(
brice hansemann, a meaux, prazaru margarita, adi popa, chica florin, tavu anarena, adan alexandra, kati enesa, alin alexandro, en reunion, en reunion)
```

**Comment by KennethEnevoldsen** [comment]
You can redefine the tokenizer which you spacy pipeline uses. So I don't see why it shouldn't be, but then it might simply be easier to then simply use the huggingface pipeline. The benefit of using spacy-wrap is that it allows you to integrate these models with other spacy tools.

**Comment by KennethEnevoldsen** [comment]
As the main issue is fixed I will close this issue.
